# -*- coding: utf-8 -*-
"""Factors of a number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16lb_DmdksnaFGRbP87pd3G-fvWccoUBC
"""

#Factors of a number
x = int(input("enter the number"))

[i for i in range(1,x//2+1) if x % i ==0]

