# -*- coding: utf-8 -*-
"""GCD with and without recursion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l5uxOhn5YZopdFZgj8v7wazdj2LQ9jc2
"""

# GCD

def gcd(x,y):
  z = [i for i in  range(1,min(x,y)+1) if x%i ==0 and y%i==0]
  return(z[-1])

gcd(12,6)

# gcd with recursion

def gcd(a,b):
    if(b==0):
        return a
    else:
        return gcd(b,a%b)
a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
GCD=gcd(a,b)
print("GCD is: ")
print(GCD)

