# -*- coding: utf-8 -*-
"""to Determine Whether a Given Number is Even or Odd Recursively.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xI5AWmJEFGqkOTyVEAohmbC8YDvZQk_j
"""

#to Determine Whether a Given Number is Even or Odd Recursively

# without recursion
n=11
if n%2 ==0:
  print("even")
else:
  print("odd")

# recursion
def check(n):
    if (n < 2):
        return (n % 2 == 0)
    return (check(n - 2))
n=int(input("Enter number:"))
if(check(n)==True):
      print("Number is even!")
else:
      print("Number is odd!")