# -*- coding: utf-8 -*-
"""to Determine How Many Times a Given Letter Occurs in a String Recursively.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sahY5s_xz-QHImclviz6FXOHDt_ry3Rs
"""

#to Determine How Many Times a Given Letter Occurs in a String Recursively

def check(string,ch):
  #base case
  if not string:
    return 0
  elif string[0] ==ch:
    return(1 + check(string[1:],ch))
  else:
    return(check(string[1:],ch))

string=input("Enter string:")
ch=input("Enter character to check:")
print("Count is:")
print(check(string,ch))

