# -*- coding: utf-8 -*-
"""to Find the Sum of the Digits of the Number Recursively.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OXEHN_e-zfGRYgWEEEQ_JcdFGNo5mxh1
"""

#to Find the Sum of the Digits of the Number Recursively

def sum_of_digits_recursively(n):
  if n//10 ==0:
    return(n)
  else:
    return(n%10 +sum_of_digits_recursively(n//10))

sum_of_digits_recursively(123)

