# -*- coding: utf-8 -*-
"""to Find the LCM of Two Numbers without recursion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vbV74Ua9aZbptijbUpTKtDpqi7RWxIn-
"""

#to Find the LCM of Two Numbers without Recursion

x = int(input("enter the first number"))
y = int(input("enter the second number"))
def lcm(x,y):
    z= [i for i in range(2,max(x,y)+1) if  x%i ==0 and y%i ==0]
    if not z:
      return(x*y)
    else:
      return(z[0])
lcm(x,y)

