# -*- coding: utf-8 -*-
"""to Find if a Number is Prime or Not Prime without  Recursion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vViReQKP7EVaziDBzox3vNBzqiL-o8x_
"""

#to Find if a Number is Prime or Not Prime without Recursion

# if a number is divisible by 1 and from itself only then it is a prime number
#  to check, we have to see  whether number n is divisible from 1 to n-1 or n/2

def prime_check(n):
    z=[i for i in range(2,n//2+1) if n%i == 0 ]
    if not z:
      return("prime  number")
    else:
      return("not prime")

prime_check(11)

