# -*- coding: utf-8 -*-
"""to Find the Fibonacci Series Using Recursion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TDZSq9BHvnOPbnJKmDMlIATCIHZuxneZ
"""

#to Find the Fibonacci Series Using Recursion

def fibseries(n):
  #base case
  if n == 0:
    return None
  elif n ==1:
    return(0)
  elif n==2:
    return(1)
  else:
    return(fibseries(n-1) +fibseries(n-2) )
 
def printseries():
  n = int(input("no of terms in fibonacci series you want"))
  return[fibseries(i) for i in range(n)]

printseries()

