# -*- coding: utf-8 -*-
"""to Find the Sum of Elements in a List Recursively.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1stW3DMeRq7F1TmyrL2JFwU2RuU48L5mn
"""

#to Find the Sum of Elements in a List Recursively

x = [1,2,3,11,6] # this is list

def sum_of_elements_of_list(x):
  if len(x)==1:
    return(x[0])
  else:
    return(x[0]+ sum_of_elements_of_list(x[1:]))

sum_of_elements_of_list(x)

