# -*- coding: utf-8 -*-
"""to Find the Area of a Rectangle Using Classes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rF2Y2rhn5hSb6SbR-Zi8pIf-rpJXsXxz
"""

#to Find the Area of a Rectangle Using Classes

"""1. Take the value of length and breadth from the user.
2. Create a class and using a constructor initialise values of that class.
3. Create a method called as area and return the area of the class.
4. Create an object for the class.
5. Using the object, call the method area() with the parameters as the length and breadth taken from the user.
6. Print the area. 
"""

l = int(input("enter the length"))
b =int(input("enter the breadth"))


class Area_0f_rectangle:
  def __init__(self,l,b):
    self.l =l
    self.b =b
  def area(self):
    return(self.l*self.b)

obj = Area_0f_rectangle(l,b)
obj.area()

