# -*- coding: utf-8 -*-
"""Calculate the Average of Numbers in a Given List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kZ2OuEvzrBx3pVSb8eSXJRP8WA2s98im
"""

# to Calculate the Average of Numbers in a Given List

#1.	Take the number of elements to be stored in the list as input.
n = int(input("the number of elements to be stored in the list "))

#2.	Use a for loop to input elements into the list.

# 1 way with loop
y =[]
for i in range(n):                      # 3 loop
    x= int(input("enter the number"))     # 1 input elements
    y.append(x)                           #2  store the elements

# 2 nd way using list comprehension
z =[int(input("enter the number")) for i in range(n)]

#3.	Calculate the total sum of elements in the list.

s = sum(z)

#4.	Divide the sum by total number of elements in the list.

average= s/n

print(average)

# full code
n = int(input("the number of elements to be stored in the list: "))
z =[int(input("enter the number:")) for i in range(n)]
avg = print(round(sum(z)/n,2))

