# -*- coding: utf-8 -*-
"""Python Program to Check Whether a Number is Positive or Negative.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BAF7br7_O9vQZNeCZV1brQqDL0hq7J9t
"""

#Python Program to Check Whether a Number is Positive or Negative

def check_positive_or_negatve(n):
  if n ==0:
    return("Neither negative or positive")
  elif n>0:
    return("Positive")
  else:
    return("Negative")



