# -*- coding: utf-8 -*-
"""Python Program to Print all Numbers in a Range Divisible by a Given Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rMRRf2DMlc7S481tPsc9mlwVT9WrKvqg
"""

#Python Program to Print all Numbers in a Range Divisible by a Given Number

# using while loop
x =int(input("enter lower limit"))
y =int(input("enter upper limit")) 
n =int(input("enter number which will divide each number from x to y"))
while x<=y:
    if x%n ==0:
        print(x)
        x = x+1
    else:
      x = x+1

# using for loop
x =int(input("enter lower limit"))
y =int(input("enter upper limit")) 
n =int(input("enter number which will divide each number from x to y"))
for i in range(x,y+1):
  if i%n ==0:
    print(i)

