# -*- coding: utf-8 -*-
"""Python Program to Read Two Numbers and Print Their Quotient and Remainder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t0-3H170ijeEkq3UHl6_txvSGoODxNI3
"""

#Python Program to Read Two Numbers and Print Their Quotient and Remainder

a =[int(input("enter the number")) for i in  range(2)]
print('"Remainder":{}, "Quotient"":{}'.format(a[0]%a[1],a[0]//a[1]))