# -*- coding: utf-8 -*-
"""Python Program to Print Odd Numbers Within a Given Range.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pWfSyMFptH1T34UIQcUG38e-LTqUoee
"""

#Python Program to Print Odd Numbers Within a Given Range

a = [int(input("enter the lower and upper range")) for i in range(2)]
for _ in  range(a[0],a[1]):
  if _%2 ==1:
    print(_)

