# -*- coding: utf-8 -*-
"""Python Program to Take in the Marks of 5 Subjects and Display the Grade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UDECmYojL00xirJFIsw74nvCfSKk9Jys
"""

#Python Program to Take in the Marks of 5 Subjects and Display the Grade

def display_grade(n):
  a = []
  for i in range(n):
      a.append(int(input("enter the marks:")))
  if sum(a)/n >=90 and sum(a)/n<=100:
    print('A')
  elif sum(a)/n>=80 and sum(a)/n<90:
    print('B')
  elif sum(a)/n>=70 and sum(a)/n<80:
    print('C')
  elif sum(a)/n>=60 and sum(a)/n<70:
    print('D')
  else:
    print("Fail")

display_grade(5)

# using list comprehension
def gradeassingment(n):
  a=[int(input("enter the marks:"))for i in range(n)]
  if sum(a)/n >=90 and sum(a)/n<=100:
    print('A')
  elif sum(a)/n>=80 and sum(a)/n<90:
    print('B')
  elif sum(a)/n>=70 and sum(a)/n<80:
    print('C')
  elif sum(a)/n>=60 and sum(a)/n<70:
    print('D')
  else:
    print("Fail")

