# -*- coding: utf-8 -*-
"""Python Program to swap the Values of Two Numbers Without Using a Temporary Variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D6M_gsy_GefnYQCqxDSt-NAcckuCfSLR
"""

#Python Program to swap the Values of Two Numbers Without Using a Temporary Variable

#1.	Take the values of both the elements from the user.
#2.	Store the values in separate variables.

x = int(input("enter the first number"))
y = int (input("enter the second number"))

#3.	Add both the variables and store it in the first variable.
x= x+y

#Subtract the second variable from the first and store it in the second variable.
y = x-y

#5.	Then, subtract the first variable from the second variable and store it in the first variable.
x = x -y

print(x,y)

# full code
x = int(input("enter the first number"))
y = int (input("enter the second number"))
x= x+y
y = x-y
x = x -y
print(x,y)

