# -*- coding: utf-8 -*-
"""Python Program to Read a Mumber n and Compute n+nn+nnn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xo0UXWpsbFIMohumaxLJUGWQg34dceuf
"""

#Python Program to Read a Mumber n and Compute n+nn+nnn

# if we want to compute  n+ n*n + n*n*n
def func(n):
  return( n + n*n +n*n*n)

func(5)

# if we want to  compute  n +nn +nnn
def func2(n):
 
  temp2 = str(n)+ str(n)
  temp3 = str(n)+ str(n)+ str(n)
  return( n + int(temp2) + int(temp3))

func2(5)

