# -*- coding: utf-8 -*-
"""swapping with temp variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AtdrCXGAoniOcQRxZ6W4yCQOBp1etLTK
"""

# swapping with temp variable

a = 3
b=5
c= b
b= a
a= c

print('"a":{},"b": {}'.format(a,b))

