# -*- coding: utf-8 -*-
"""To check a leap year.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OktWkY1fBWAD3YEHM0R8If9tDmw4qN-8
"""

def leap_year_checking(x):
  if x % 4 ==0:
    print("{} is a leap year".format(x))
  else:
    print("{} is not a leap year".format(x))