# -*- coding: utf-8 -*-
"""To check a number even or odd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DcQI1M0J-u72i18kCslSKnmKqm9EzZBF
"""

def check_a_no_even_or_odd(x):
  if x%2 == 1:
    print("{} is Odd".format(x))
  else:
    print("{} is Even".format(x))