# -*- coding: utf-8 -*-
"""Replace all Occurrences of ‘a’ with $ in a String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zan8SrSb41sgj7xYqlOo3eBfQlClb8VT
"""

#Replace all Occurrences of ‘a’ with $ in a String

# use  replace("a","$")

