# -*- coding: utf-8 -*-
"""to Remove the nth Index Character from a Non-Empty String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-U3spl8qeqH70o2uwjYKjoo4SMxbR9KT
"""

#to Remove the nth Index Character from a Non-Empty String

""" Take a string from the user and store it in a variable.
2. Take the index of the character to remove.
3. Pass the string and the index as arguments to a function named remove.
4. In the function, the string should then be split into two halves before the index character and after the index character.
5. These two halves should then be merged together.
6. Print the modified string. """

def remove(string,index):# 3

  divide =  string[:index] +string[index+1:]  #4,5
  return(divide)
string = input("enter the string") #1
index = int(input("enter the index"))#2
remove(string,index)



