# -*- coding: utf-8 -*-
"""to Add a Key-Value Pair to the Dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ExIoFlaLnP7sY0iwrdZm2TEpKdXiVlTK
"""

#to Add a Key-Value Pair to the Dictionary

'''1. Take a key-value pair from the user and store it in separate variables.
2. Declare a dictionary and initialize it to an empty dictionary.
3. Use the update() function to add the key-value pair to the dictionary.
4. Print the final dictionary.'''

#1
key = input("enter the key")
value = input("enter the vallue")
# 2
d ={}

d.update({key:value})
print(d)

