# -*- coding: utf-8 -*-
"""to Concatenate Two Dictionaries Into One.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1haPo7uLH6TZa2EclFYgNqAp9VIOSEQ89
"""

#to Concatenate Two Dictionaries Into One

d1={'A':1,'B':2}
d2={'C':3}
d1.update(d2)
print("Concatenated dictionary is:")
print(d1)

