# -*- coding: utf-8 -*-
"""to Check if a Given Key Exists in a Dictionary or Not.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nKUtjEV0Wo9B1olTryn8j1tuwLIBr1ns
"""

#to Check if a Given Key Exists in a Dictionary or Not

d={'A':1,'B':2,'C':3}
key=input("Enter key to check:")
if key in d :
    print("key exist")
else:
  print("key not exist")

