# -*- coding: utf-8 -*-
"""to Find the Second Largest Number in a List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/103q-jvE3xE4ONaAgUwbeHsAnnwuLXVPn
"""

#to Find the Second Largest Number in a List

#  use the .sort or sorted(list) and  return the second last number  from the list