# -*- coding: utf-8 -*-
"""to Find the Largest Number in a List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LPAwhHh9IjAzFhPMrNJIQHdBe-tiNimo
"""

#to Find the Largest Number in a List

# 1st Method

a = [1,2,4,12,3,24]
store = []
for i in range(len(a)-1):
  if a[i] > a[i+1]:
    store = a[i]
  else:
    store = a[i+1]
print(store)

# 2nd Method using function
def largest_no(a):
  store = []
  for i in range(len(a)-1):
    if a[i]> a[i+1]:
      store = a[i]
    else:
      store = a[i+1]
  return(store)

# 3rd method
# sort the list using .sort or sorted(list) and print the last number