# -*- coding: utf-8 -*-
"""to Merge Two Lists and Sort it.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MrtAPG5ltGaoZUaiTtsjQuSKPAzhzBKQ
"""

# to Merge Two Lists and Sort it

a = [1,2,25]
b = [3,8,12]

z = a+b # merge

z

z.sort() # sort

z

