# -*- coding: utf-8 -*-
"""to Put Even and Odd elements in a List into Two Different Lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_fmZlZA35Tvjl16tOHD3nbKlJnZgqV07
"""

#to Put Even and Odd elements in a List into Two Different Lists

#method1 
even_list = [i for i in range(0,10,2)]# 11 = n+1
odd_list = [i for i in range(1,10,2)]# 11 = n+1

#method 2
def put_even_odd_no__in_sep_list():
  z = list(input("enter the list"))
  even_list = [i for i in range(0,len(z),2)]
  odd_list = [i for i in range(1,len(z),2)]
  return(even_list,odd_list)

